[package]
name = "simple-secrets"
version = "0.1.0"
authors = ["Tim Shadel <tim@daylogger.com>"]
edition = "2018"

[dependencies]
data-encoding = "^2.1.2"
rand = "^0.6"
rmp-serde = "^0.13"
rust-crypto = "^0.2"
serde = "^1.0"
serde_bytes = "^0.10"
